# Generated by Django 2.2.10 on 2020-05-19 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200519_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topping',
            old_name='name',
            new_name='topping_name',
        ),
    ]
