# Generated by Django 2.2.10 on 2020-05-19 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200519_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='rtoppings',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='stoppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rtoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
    ]
