# Generated by Django 2.2.10 on 2020-05-19 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200519_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='rtoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, null=True, related_name='stoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
    ]
