# Generated by Django 2.2.10 on 2020-05-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200519_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='rtoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='stoppings', to='orders.Topping', verbose_name='Toppings'),
        ),
    ]
