# Generated by Django 2.2.10 on 2020-05-19 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200519_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='category',
            field=models.CharField(blank=True, choices=[('Pizza', 'Pizza'), ('Pasta', 'Pasta'), ('Subs', 'Subs'), ('Salad', 'Salad'), ('Dinner_Platter', 'Dinner_Platter'), ('Topping', 'Topping'), ('Extra', 'Extra'), ('Dessert', 'Dessert'), ('Pastry', 'Pastry'), ('Main', 'Main'), ('Appetizer', 'Appetizer'), ('Side', 'Side'), ('Miscellaneous', 'Miscellaneous')], help_text='Enter the category of the menu item', max_length=36, null=True),
        ),
    ]
