# Generated by Django 2.2.10 on 2020-05-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200520_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='rpizzas', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='spizzas', to='orders.Topping'),
        ),
    ]
