# Generated by Django 2.2.10 on 2020-05-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200520_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subs',
            name='extras',
        ),
        migrations.AddField(
            model_name='subs',
            name='sub_extras',
            field=models.ManyToManyField(blank=True, related_name='sub_extra', to='orders.Extras'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='rpizza_toppings', to='orders.Topping'),
        ),
        migrations.AlterField(
            model_name='sicilian_pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='spizza_toppings', to='orders.Topping'),
        ),
    ]
