# Generated by Django 2.2.10 on 2020-05-22 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20200520_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('menu_item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Menu_Item')),
            ],
            bases=('orders.menu_item',),
        ),
    ]
