# Generated by Django 2.2.10 on 2020-05-22 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
