# Generated by Django 2.2.10 on 2020-05-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, help_text='Enter the category of the menu item', max_length=36, null=True)),
                ('name', models.CharField(help_text='Enter name of the menu item', max_length=128)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('sizes', models.CharField(blank=True, help_text='Enter the allowable sizes of the menu item', max_length=4, null=True)),
            ],
        ),
    ]
