# Generated by Django 2.2.10 on 2020-05-22 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='sizes',
            field=models.CharField(blank=True, help_text='Enter the allowable sizes of the menu item', max_length=4, null=True),
        ),
    ]
