# Generated by Django 2.2.10 on 2020-05-22 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200521_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('XL', 'Extra_Large')], help_text='Enter the allowable sizes of the menu item', max_length=4, null=True),
        ),
    ]
