# Generated by Django 2.2.10 on 2020-05-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200524_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu_item',
            name='num_toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='menu_item',
            name='toppings',
            field=models.CharField(blank=True, help_text='Enter toppings', max_length=400, null=True),
        ),
    ]
