# Generated by Django 2.2.10 on 2020-05-26 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_remove_orderitem_ptoppings'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ptoppings',
            field=models.CharField(blank=True, help_text='Enter toppings', max_length=400, null=True),
        ),
    ]
