# Generated by Django 2.2.10 on 2020-05-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200526_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='num_toppings',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
