# Generated by Django 2.2.10 on 2020-05-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200526_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='num_toppings',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
