# Generated by Django 2.2.10 on 2020-05-26 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20200526_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='ptoppings',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
