# Generated by Django 2.2.10 on 2020-05-26 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20200526_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='topping',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ptoppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ptoppings',
            field=models.ManyToManyField(blank=True, related_name='pizza_toppings', to='orders.Topping'),
        ),
    ]
