# Generated by Django 2.2.10 on 2020-05-26 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ptoppings',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='ptoppings',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
