# Generated by Django 2.2.10 on 2020-05-27 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20200526_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='sizes',
            field=models.IntegerField(blank=True, help_text='Enter the allowable sizes of the menu item', null=True),
        ),
    ]
