# Generated by Django 2.2.10 on 2020-05-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200526_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='is_topping',
            field=models.BooleanField(default=False),
        ),
    ]
