# Generated by Django 2.2.10 on 2020-05-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_orderitem_is_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item',
            field=models.ManyToManyField(blank=True, to='orders.Menu_Item'),
        ),
    ]
