# Generated by Django 2.2.10 on 2020-05-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0036_auto_20200528_0838'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='extras',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
