# Generated by Django 2.2.10 on 2020-06-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0038_orderitem_extras_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
