# Generated by Django 2.2.10 on 2020-06-01 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_delete_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('Sm', 'Small'), ('Md', 'Medium'), ('Lg', 'Large'), ('XL', 'Extra_Large')], help_text='Enter the allowable sizes of the menu item', max_length=4, null=True),
        ),
    ]
