# Generated by Django 2.2.10 on 2020-06-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_auto_20200601_1533'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dinner_Platter',
        ),
        migrations.DeleteModel(
            name='Items',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.RemoveField(
            model_name='sicilian_pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='subs',
            name='sub_extras',
        ),
        migrations.AlterField(
            model_name='menu_item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('Sm', 'Small'), ('Md', 'Medium'), ('Lg', 'Large'), ('XL', 'Extra_Large')], help_text='Enter the allowable sizes                                             of the menu item', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Sicilian_Pizza',
        ),
        migrations.DeleteModel(
            name='Subs',
        ),
    ]
